# Generated by Django 5.0 on 2024-08-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartward', '0008_patient_remove_appointment_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_reason',
            field=models.CharField(choices=[('blood_test', 'Blood Test'), ('ct_scan', 'CT Scan'), ('doctor_consultation', 'Doctor Consultation'), ('x_rays', 'X-Rays'), ('blood_pressure_measurement', 'Blood Pressure Measurement'), ('urinalysis', 'Urinalysis'), ('eye_test', 'Eye Test')], default='doctor_consultation', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartward.patient'),
        ),
    ]
