# Generated by Django 5.0 on 2024-08-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartward', '0009_appointment_booking_reason_alter_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='booking_reason',
        ),
    ]
