# Generated by Django 5.0 on 2024-10-03 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartward', '0012_alter_patient_emergency_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('vitals', models.JSONField()),
                ('visit_results', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartward.patient')),
            ],
            options={
                'permissions': [('can_write_vitals', 'Can write vitals'), ('can_access_visit_results', 'Can access visit results')],
            },
        ),
    ]
